"""empty message

Revision ID: 121dbeb6d435
Revises: f1c2b35c24a0
Create Date: 2022-03-02 22:41:45.222828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121dbeb6d435'
down_revision = 'f1c2b35c24a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guess', 'accuracy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guess', sa.Column('accuracy', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
