"""empty message

Revision ID: f1c2b35c24a0
Revises: c6303c5ac47b
Create Date: 2022-03-02 22:17:40.485933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c2b35c24a0'
down_revision = 'c6303c5ac47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('creator_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'creator_id')
    # ### end Alembic commands ###
